name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install-crunch
      run: sudo apt install crunch
    - name: generate-wordlist
      run: 
          if [ ! -e "wordlist.dat" ]; then\n
            \tcrunch 10 10 abcd012345 -o wordlist.dat\n
          else\n
            echo "File exists"\n
          fi
    - name: make
      run: make
    - name: make benchmark
      run: make benchmark
    - name: test
      run: ./iron -h 9F84FFBDC1319543B91DF8EB21D5DE3B -d wordlist.dat
