name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make benchmark
      run: make benchmark
    - name: test
      run: ./mdcrack -h 9F84FFBDC1319543B91DF8EB21D5DE3B -d unknown_file.txt
