name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install crunch
      run: sudo apt install -y crunch
    - name: Download Wordlist
      run: |
        curl https://raw.githubusercontent.com/praetorian-inc/Hob0Rules/master/wordlists/rockyou.txt.gz -o rockyou.txt.gz
        gzip -d rockyou.txt.gz
    - name: Build
      run: make
    - name: Test SHA-1
      run: ./iron -h 3ffbffb9855e24faacc53a186bdd387142e75bd3 -d rockyou.txt -t SHA1
    - name: Test MD5
      run: ./iron -h 5d61cd72e5a14814f3ac6fccf903e031 -d rockyou.txt -t MD5
