name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  test-iron:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install-crunch
      run: sudo apt install crunch
    - name: generate-wordlist
      run: 
          if [ ! -e "wordlist.dat" ]; then crunch 8 8 0123456789 -o wordlist.dat; else echo "File exists"; fi
    - name: make
      run: make
    - name: test
      run: ./iron -h 9F84FFBDC1319543B91DF8EB21D5DE3B -d wordlist.dat
